name: CI

on:
  pull_request:
    types: [synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test